-- ============================================================================
-- ACCESS ROLES — Snowflake RBAC
-- Generated for: {{COMPANY_NAME}}
-- Environment:   {{ENV}}
-- ============================================================================
-- IMPORTANT: Run this script with SECURITYADMIN or USERADMIN role.
-- ============================================================================

USE ROLE SECURITYADMIN;

-- ============================================================================
-- 1. DATABASE-LEVEL ACCESS ROLES
-- ============================================================================
-- One RO (read-only) and one RW (read-write) role per database per environment.

-- ---- BRONZE DATABASE ----
CREATE ROLE IF NOT EXISTS AR_{{ENV}}_BRONZE_ALL_RO
    COMMENT = 'Read-only access to all schemas in {{ENV}}_BRONZE_DB';

CREATE ROLE IF NOT EXISTS AR_{{ENV}}_BRONZE_ALL_RW
    COMMENT = 'Read-write access to all schemas in {{ENV}}_BRONZE_DB';

-- Grant database usage
GRANT USAGE ON DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RO;
GRANT USAGE ON DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RW;

-- Grant schema usage (all current schemas)
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RW;

-- Grant on future schemas
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RO;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RW;

-- RO grants: SELECT only
GRANT SELECT ON ALL TABLES IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RO;
GRANT SELECT ON ALL VIEWS IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RO;
GRANT SELECT ON FUTURE TABLES IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RO;
GRANT SELECT ON FUTURE VIEWS IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RO;

-- RW grants: SELECT + DML + DDL
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RW;
GRANT SELECT ON ALL VIEWS IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RW;
GRANT SELECT ON FUTURE VIEWS IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON FUTURE SCHEMAS IN DATABASE {{ENV}}_BRONZE_DB TO ROLE AR_{{ENV}}_BRONZE_ALL_RW;


-- ---- SILVER DATABASE ----
-- (Repeat the same pattern for SILVER)
CREATE ROLE IF NOT EXISTS AR_{{ENV}}_SILVER_ALL_RO
    COMMENT = 'Read-only access to all schemas in {{ENV}}_SILVER_DB';
CREATE ROLE IF NOT EXISTS AR_{{ENV}}_SILVER_ALL_RW
    COMMENT = 'Read-write access to all schemas in {{ENV}}_SILVER_DB';

GRANT USAGE ON DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RO;
GRANT USAGE ON DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RW;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RW;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RO;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RW;
GRANT SELECT ON ALL TABLES IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RO;
GRANT SELECT ON ALL VIEWS IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RO;
GRANT SELECT ON FUTURE TABLES IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RO;
GRANT SELECT ON FUTURE VIEWS IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RO;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RW;
GRANT SELECT ON ALL VIEWS IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RW;
GRANT SELECT ON FUTURE VIEWS IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON FUTURE SCHEMAS IN DATABASE {{ENV}}_SILVER_DB TO ROLE AR_{{ENV}}_SILVER_ALL_RW;


-- ---- GOLD DATABASE ----
-- (Repeat the same pattern for GOLD)
CREATE ROLE IF NOT EXISTS AR_{{ENV}}_GOLD_ALL_RO
    COMMENT = 'Read-only access to all schemas in {{ENV}}_GOLD_DB';
CREATE ROLE IF NOT EXISTS AR_{{ENV}}_GOLD_ALL_RW
    COMMENT = 'Read-write access to all schemas in {{ENV}}_GOLD_DB';

GRANT USAGE ON DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RO;
GRANT USAGE ON DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RW;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RW;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RO;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RW;
GRANT SELECT ON ALL TABLES IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RO;
GRANT SELECT ON ALL VIEWS IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RO;
GRANT SELECT ON FUTURE TABLES IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RO;
GRANT SELECT ON FUTURE VIEWS IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RO;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RW;
GRANT SELECT ON ALL VIEWS IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RW;
GRANT SELECT ON FUTURE VIEWS IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON FUTURE SCHEMAS IN DATABASE {{ENV}}_GOLD_DB TO ROLE AR_{{ENV}}_GOLD_ALL_RW;


-- ============================================================================
-- 2. SCHEMA-LEVEL ACCESS ROLES (if schema-level hiding is required)
-- ============================================================================
-- Create per-schema roles only for schemas that need isolation.
-- Replace {{SCHEMA}} with the actual schema name (e.g., SAP, SALESFORCE).

-- CREATE ROLE IF NOT EXISTS AR_{{ENV}}_{{DB}}_{{SCHEMA}}_RO
--     COMMENT = 'Read-only access to {{SCHEMA}} schema in {{ENV}}_{{DB}}_DB';
-- CREATE ROLE IF NOT EXISTS AR_{{ENV}}_{{DB}}_{{SCHEMA}}_RW
--     COMMENT = 'Read-write access to {{SCHEMA}} schema in {{ENV}}_{{DB}}_DB';
--
-- GRANT USAGE ON DATABASE {{ENV}}_{{DB}}_DB TO ROLE AR_{{ENV}}_{{DB}}_{{SCHEMA}}_RO;
-- GRANT USAGE ON SCHEMA {{ENV}}_{{DB}}_DB.{{SCHEMA}} TO ROLE AR_{{ENV}}_{{DB}}_{{SCHEMA}}_RO;
-- GRANT SELECT ON ALL TABLES IN SCHEMA {{ENV}}_{{DB}}_DB.{{SCHEMA}} TO ROLE AR_{{ENV}}_{{DB}}_{{SCHEMA}}_RO;
-- GRANT SELECT ON FUTURE TABLES IN SCHEMA {{ENV}}_{{DB}}_DB.{{SCHEMA}} TO ROLE AR_{{ENV}}_{{DB}}_{{SCHEMA}}_RO;


-- ============================================================================
-- 3. UNMASK ROLE (if dynamic data masking is required)
-- ============================================================================
-- Only roles granted AR_{{ENV}}_UNMASK will see unmasked PII data.

-- CREATE ROLE IF NOT EXISTS AR_{{ENV}}_UNMASK
--     COMMENT = 'Exemption role for dynamic data masking in {{ENV}}';


-- ============================================================================
-- 4. GRANT ALL ACCESS ROLES TO SYSADMIN (best practice)
-- ============================================================================
GRANT ROLE AR_{{ENV}}_BRONZE_ALL_RO TO ROLE SYSADMIN;
GRANT ROLE AR_{{ENV}}_BRONZE_ALL_RW TO ROLE SYSADMIN;
GRANT ROLE AR_{{ENV}}_SILVER_ALL_RO TO ROLE SYSADMIN;
GRANT ROLE AR_{{ENV}}_SILVER_ALL_RW TO ROLE SYSADMIN;
GRANT ROLE AR_{{ENV}}_GOLD_ALL_RO TO ROLE SYSADMIN;
GRANT ROLE AR_{{ENV}}_GOLD_ALL_RW TO ROLE SYSADMIN;
