-- ============================================================================
-- COMPLETE RBAC SAMPLE — MedCare Health Systems
-- Environment: PROD
-- ============================================================================
-- This is a fully worked example for a healthcare company with:
--   - 4 source systems (Epic EHR, SAP Billing, Kronos, Flat Files)
--   - 3 environments (DEV, QA, PROD)
--   - PII data requiring dynamic masking (SSN, Patient Name, DOB, Email, Phone)
--   - Schema-level hiding required
--   - Teams: Data Engineering (5), Analytics (8), Managers (3), Data Science (2)
--   - Access roles implemented as DATABASE ROLES (scoped to owning database)
-- ============================================================================


-- ============================================================================
-- SECTION 1: ACCESS ROLES (DATABASE ROLES)
-- ============================================================================
-- Database roles are created by the database owner (SYSADMIN).
-- They automatically have USAGE on their owning database — no explicit grant needed.

USE ROLE SYSADMIN;

-- ---- Database-Level Access Roles: PROD_BRONZE_DB ----
CREATE DATABASE ROLE IF NOT EXISTS PROD_BRONZE_DB.AR_ALL_RO
    COMMENT = 'RO access to all schemas in PROD_BRONZE_DB';
CREATE DATABASE ROLE IF NOT EXISTS PROD_BRONZE_DB.AR_ALL_RW
    COMMENT = 'RW access to all schemas in PROD_BRONZE_DB';

GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_BRONZE_DB TO DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RO;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_BRONZE_DB TO DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_BRONZE_DB TO DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RW;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_BRONZE_DB TO DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RW;

GRANT SELECT ON ALL TABLES IN DATABASE PROD_BRONZE_DB TO DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RO;
GRANT SELECT ON FUTURE TABLES IN DATABASE PROD_BRONZE_DB TO DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RO;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE PROD_BRONZE_DB TO DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE PROD_BRONZE_DB TO DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE PROD_BRONZE_DB TO DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RW;

-- ---- Schema-Level Access Roles (for sensitive schemas in PROD_BRONZE_DB) ----
CREATE DATABASE ROLE IF NOT EXISTS PROD_BRONZE_DB.AR_EPIC_RO
    COMMENT = 'RO access to EPIC schema in PROD_BRONZE_DB';
CREATE DATABASE ROLE IF NOT EXISTS PROD_BRONZE_DB.AR_EPIC_RW
    COMMENT = 'RW access to EPIC schema in PROD_BRONZE_DB';
CREATE DATABASE ROLE IF NOT EXISTS PROD_BRONZE_DB.AR_SAP_RO
    COMMENT = 'RO access to SAP schema in PROD_BRONZE_DB';
CREATE DATABASE ROLE IF NOT EXISTS PROD_BRONZE_DB.AR_SAP_RW
    COMMENT = 'RW access to SAP schema in PROD_BRONZE_DB';

GRANT USAGE ON SCHEMA PROD_BRONZE_DB.EPIC TO DATABASE ROLE PROD_BRONZE_DB.AR_EPIC_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD_BRONZE_DB.EPIC TO DATABASE ROLE PROD_BRONZE_DB.AR_EPIC_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD_BRONZE_DB.EPIC TO DATABASE ROLE PROD_BRONZE_DB.AR_EPIC_RO;
GRANT USAGE ON SCHEMA PROD_BRONZE_DB.EPIC TO DATABASE ROLE PROD_BRONZE_DB.AR_EPIC_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PROD_BRONZE_DB.EPIC TO DATABASE ROLE PROD_BRONZE_DB.AR_EPIC_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PROD_BRONZE_DB.EPIC TO DATABASE ROLE PROD_BRONZE_DB.AR_EPIC_RW;

GRANT USAGE ON SCHEMA PROD_BRONZE_DB.SAP TO DATABASE ROLE PROD_BRONZE_DB.AR_SAP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD_BRONZE_DB.SAP TO DATABASE ROLE PROD_BRONZE_DB.AR_SAP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD_BRONZE_DB.SAP TO DATABASE ROLE PROD_BRONZE_DB.AR_SAP_RO;
GRANT USAGE ON SCHEMA PROD_BRONZE_DB.SAP TO DATABASE ROLE PROD_BRONZE_DB.AR_SAP_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PROD_BRONZE_DB.SAP TO DATABASE ROLE PROD_BRONZE_DB.AR_SAP_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PROD_BRONZE_DB.SAP TO DATABASE ROLE PROD_BRONZE_DB.AR_SAP_RW;

-- ---- Database-Level Access Roles: PROD_SILVER_DB ----
CREATE DATABASE ROLE IF NOT EXISTS PROD_SILVER_DB.AR_ALL_RO
    COMMENT = 'RO access to all schemas in PROD_SILVER_DB';
CREATE DATABASE ROLE IF NOT EXISTS PROD_SILVER_DB.AR_ALL_RW
    COMMENT = 'RW access to all schemas in PROD_SILVER_DB';

GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_SILVER_DB TO DATABASE ROLE PROD_SILVER_DB.AR_ALL_RO;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_SILVER_DB TO DATABASE ROLE PROD_SILVER_DB.AR_ALL_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_SILVER_DB TO DATABASE ROLE PROD_SILVER_DB.AR_ALL_RW;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_SILVER_DB TO DATABASE ROLE PROD_SILVER_DB.AR_ALL_RW;

GRANT SELECT ON ALL TABLES IN DATABASE PROD_SILVER_DB TO DATABASE ROLE PROD_SILVER_DB.AR_ALL_RO;
GRANT SELECT ON FUTURE TABLES IN DATABASE PROD_SILVER_DB TO DATABASE ROLE PROD_SILVER_DB.AR_ALL_RO;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE PROD_SILVER_DB TO DATABASE ROLE PROD_SILVER_DB.AR_ALL_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE PROD_SILVER_DB TO DATABASE ROLE PROD_SILVER_DB.AR_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE PROD_SILVER_DB TO DATABASE ROLE PROD_SILVER_DB.AR_ALL_RW;

-- ---- Unmask Role (database role in PROD_SILVER_DB where PII resides) ----
CREATE DATABASE ROLE IF NOT EXISTS PROD_SILVER_DB.AR_UNMASK
    COMMENT = 'Exemption role for data masking — see unmasked PII';

-- ---- Database-Level Access Roles: PROD_GOLD_DB ----
CREATE DATABASE ROLE IF NOT EXISTS PROD_GOLD_DB.AR_ALL_RO
    COMMENT = 'RO access to all schemas in PROD_GOLD_DB';
CREATE DATABASE ROLE IF NOT EXISTS PROD_GOLD_DB.AR_ALL_RW
    COMMENT = 'RW access to all schemas in PROD_GOLD_DB';

GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_GOLD_DB TO DATABASE ROLE PROD_GOLD_DB.AR_ALL_RO;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_GOLD_DB TO DATABASE ROLE PROD_GOLD_DB.AR_ALL_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_GOLD_DB TO DATABASE ROLE PROD_GOLD_DB.AR_ALL_RW;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_GOLD_DB TO DATABASE ROLE PROD_GOLD_DB.AR_ALL_RW;

GRANT SELECT ON ALL TABLES IN DATABASE PROD_GOLD_DB TO DATABASE ROLE PROD_GOLD_DB.AR_ALL_RO;
GRANT SELECT ON FUTURE TABLES IN DATABASE PROD_GOLD_DB TO DATABASE ROLE PROD_GOLD_DB.AR_ALL_RO;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE PROD_GOLD_DB TO DATABASE ROLE PROD_GOLD_DB.AR_ALL_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE PROD_GOLD_DB TO DATABASE ROLE PROD_GOLD_DB.AR_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE PROD_GOLD_DB TO DATABASE ROLE PROD_GOLD_DB.AR_ALL_RW;


-- ============================================================================
-- SECTION 2: DYNAMIC DATA MASKING POLICIES
-- ============================================================================
-- Masking policies reference the database role for unmask exemption.

USE ROLE SYSADMIN;

CREATE OR REPLACE MASKING POLICY PROD_SILVER_DB.COMMON.SSN_MASK AS
    (val STRING) RETURNS STRING ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('PROD_SILVER_DB.AR_UNMASK') THEN val
        ELSE '***-**-' || RIGHT(val, 4)
    END
    COMMENT = 'Partial mask for SSN — shows last 4 digits only';

CREATE OR REPLACE MASKING POLICY PROD_SILVER_DB.COMMON.EMAIL_MASK AS
    (val STRING) RETURNS STRING ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('PROD_SILVER_DB.AR_UNMASK') THEN val
        ELSE '****@' || SPLIT_PART(val, '@', 2)
    END
    COMMENT = 'Masks email username, preserves domain';

CREATE OR REPLACE MASKING POLICY PROD_SILVER_DB.COMMON.PHONE_MASK AS
    (val STRING) RETURNS STRING ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('PROD_SILVER_DB.AR_UNMASK') THEN val
        ELSE '***-***-' || RIGHT(val, 4)
    END
    COMMENT = 'Partial mask for phone — shows last 4 digits';

CREATE OR REPLACE MASKING POLICY PROD_SILVER_DB.COMMON.NAME_MASK AS
    (val STRING) RETURNS STRING ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('PROD_SILVER_DB.AR_UNMASK') THEN val
        ELSE '** MASKED **'
    END
    COMMENT = 'Full mask for patient names';

CREATE OR REPLACE MASKING POLICY PROD_SILVER_DB.COMMON.DOB_MASK AS
    (val DATE) RETURNS DATE ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('PROD_SILVER_DB.AR_UNMASK') THEN val
        ELSE DATE_FROM_PARTS(YEAR(val), 1, 1)
    END
    COMMENT = 'Masks DOB to year only';

-- Apply masking policies to columns (example):
-- ALTER TABLE PROD_SILVER_DB.EPIC.PATIENTS
--     MODIFY COLUMN SSN SET MASKING POLICY PROD_SILVER_DB.COMMON.SSN_MASK;
-- ALTER TABLE PROD_SILVER_DB.EPIC.PATIENTS
--     MODIFY COLUMN EMAIL SET MASKING POLICY PROD_SILVER_DB.COMMON.EMAIL_MASK;


-- ============================================================================
-- SECTION 3: FUNCTIONAL ROLES
-- ============================================================================
-- Functional roles are account-level roles. They receive database roles via
-- GRANT DATABASE ROLE ... TO ROLE.

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS FR_PROD_PLATFORM_ADMIN         COMMENT = 'PROD platform admin';
CREATE ROLE IF NOT EXISTS FR_PROD_DATA_ENGG_ADMIN        COMMENT = 'Data Engineering admin';
CREATE ROLE IF NOT EXISTS FR_PROD_DATA_ENGG_DEVELOPER    COMMENT = 'Data Engineering developer';
CREATE ROLE IF NOT EXISTS FR_PROD_ANALYTICS_ANALYST      COMMENT = 'Analytics analyst';
CREATE ROLE IF NOT EXISTS FR_PROD_ANALYTICS_VIEWER       COMMENT = 'Analytics viewer';
CREATE ROLE IF NOT EXISTS FR_PROD_MANAGERS_VIEWER        COMMENT = 'Manager viewer';
CREATE ROLE IF NOT EXISTS FR_PROD_DATA_SCIENCE_DEVELOPER COMMENT = 'Data Science developer';
CREATE ROLE IF NOT EXISTS FR_PROD_ETL_SERVICE            COMMENT = 'Fivetran ETL service';
CREATE ROLE IF NOT EXISTS FR_PROD_DBT_SERVICE            COMMENT = 'dbt service';

-- Grant database roles (access roles) to functional roles
-- NOTE: Schema hiding = Yes for MedCare. Restricted roles get per-schema
-- grants only. Admin/service roles use AR_ALL_* aggregates.

-- Platform Admin: full access + unmask
GRANT DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RW TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT DATABASE ROLE PROD_SILVER_DB.AR_ALL_RW TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT DATABASE ROLE PROD_GOLD_DB.AR_ALL_RW   TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT DATABASE ROLE PROD_SILVER_DB.AR_UNMASK  TO ROLE FR_PROD_PLATFORM_ADMIN;

-- Data Engg Admin: full access
GRANT DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RW TO ROLE FR_PROD_DATA_ENGG_ADMIN;
GRANT DATABASE ROLE PROD_SILVER_DB.AR_ALL_RW TO ROLE FR_PROD_DATA_ENGG_ADMIN;
GRANT DATABASE ROLE PROD_GOLD_DB.AR_ALL_RO   TO ROLE FR_PROD_DATA_ENGG_ADMIN;

-- Data Engg Developer: full access on Bronze+Silver
GRANT DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RW TO ROLE FR_PROD_DATA_ENGG_DEVELOPER;
GRANT DATABASE ROLE PROD_SILVER_DB.AR_ALL_RW TO ROLE FR_PROD_DATA_ENGG_DEVELOPER;

-- Analytics Analyst: Silver RO (all), Gold RO (selected schemas only — schema hiding)
GRANT DATABASE ROLE PROD_SILVER_DB.AR_ALL_RO      TO ROLE FR_PROD_ANALYTICS_ANALYST;
GRANT DATABASE ROLE PROD_GOLD_DB.AR_REPORTING_RO   TO ROLE FR_PROD_ANALYTICS_ANALYST;
GRANT DATABASE ROLE PROD_GOLD_DB.AR_PATIENT_ANALYTICS_RO TO ROLE FR_PROD_ANALYTICS_ANALYST;
-- NOTE: BILLING_ANALYTICS and COMPLIANCE schemas are HIDDEN from analysts

-- Analytics Viewer: Gold REPORTING only (schema hiding)
GRANT DATABASE ROLE PROD_GOLD_DB.AR_REPORTING_RO TO ROLE FR_PROD_ANALYTICS_VIEWER;

-- Managers Viewer: Gold REPORTING only (schema hiding)
GRANT DATABASE ROLE PROD_GOLD_DB.AR_REPORTING_RO TO ROLE FR_PROD_MANAGERS_VIEWER;

-- Data Science: Silver RO (all), Gold RW (all — needs full access for ML)
GRANT DATABASE ROLE PROD_SILVER_DB.AR_ALL_RO TO ROLE FR_PROD_DATA_SCIENCE_DEVELOPER;
GRANT DATABASE ROLE PROD_GOLD_DB.AR_ALL_RW   TO ROLE FR_PROD_DATA_SCIENCE_DEVELOPER;

-- ETL Service: full access on Bronze+Silver
GRANT DATABASE ROLE PROD_BRONZE_DB.AR_ALL_RW TO ROLE FR_PROD_ETL_SERVICE;
GRANT DATABASE ROLE PROD_SILVER_DB.AR_ALL_RW TO ROLE FR_PROD_ETL_SERVICE;

-- dbt Service: full access on Silver+Gold
GRANT DATABASE ROLE PROD_SILVER_DB.AR_ALL_RW TO ROLE FR_PROD_DBT_SERVICE;
GRANT DATABASE ROLE PROD_GOLD_DB.AR_ALL_RW   TO ROLE FR_PROD_DBT_SERVICE;

-- Hierarchy: all functional roles → SYSADMIN
GRANT ROLE FR_PROD_PLATFORM_ADMIN         TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_DATA_ENGG_ADMIN        TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_DATA_ENGG_DEVELOPER    TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_ANALYTICS_ANALYST      TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_ANALYTICS_VIEWER       TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_MANAGERS_VIEWER        TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_DATA_SCIENCE_DEVELOPER TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_ETL_SERVICE            TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_DBT_SERVICE            TO ROLE SYSADMIN;


-- ============================================================================
-- SECTION 4: WAREHOUSE GRANTS
-- ============================================================================

GRANT USAGE ON WAREHOUSE PROD_ETL_WH       TO ROLE FR_PROD_DATA_ENGG_ADMIN;
GRANT USAGE ON WAREHOUSE PROD_ETL_WH       TO ROLE FR_PROD_DATA_ENGG_DEVELOPER;
GRANT USAGE ON WAREHOUSE PROD_ETL_WH       TO ROLE FR_PROD_ETL_SERVICE;
GRANT USAGE ON WAREHOUSE PROD_ETL_WH       TO ROLE FR_PROD_DBT_SERVICE;
GRANT USAGE ON WAREHOUSE PROD_ANALYTICS_WH TO ROLE FR_PROD_ANALYTICS_ANALYST;
GRANT USAGE ON WAREHOUSE PROD_ANALYTICS_WH TO ROLE FR_PROD_ANALYTICS_VIEWER;
GRANT USAGE ON WAREHOUSE PROD_ADHOC_WH     TO ROLE FR_PROD_MANAGERS_VIEWER;
GRANT USAGE ON WAREHOUSE PROD_DS_WH        TO ROLE FR_PROD_DATA_SCIENCE_DEVELOPER;

-- Platform admin: USAGE + OPERATE
GRANT USAGE, OPERATE ON WAREHOUSE PROD_ETL_WH       TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE PROD_ANALYTICS_WH TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE PROD_ADHOC_WH     TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE PROD_DS_WH        TO ROLE FR_PROD_PLATFORM_ADMIN;
