-- ============================================================================
-- COMPLETE RBAC SAMPLE — MedCare Health Systems
-- Environment: PROD
-- ============================================================================
-- This is a fully worked example for a healthcare company with:
--   - 4 source systems (Epic EHR, SAP Billing, Kronos, Flat Files)
--   - 3 environments (DEV, QA, PROD)
--   - PII data requiring dynamic masking (SSN, Patient Name, DOB, Email, Phone)
--   - Schema-level hiding required
--   - Teams: Data Engineering (5), Analytics (8), Managers (3), Data Science (2)
-- ============================================================================

USE ROLE SECURITYADMIN;

-- ============================================================================
-- SECTION 1: ACCESS ROLES
-- ============================================================================

-- ---- Database-Level Access Roles ----
CREATE ROLE IF NOT EXISTS AR_PROD_BRONZE_ALL_RO COMMENT = 'RO access to PROD_BRONZE_DB';
CREATE ROLE IF NOT EXISTS AR_PROD_BRONZE_ALL_RW COMMENT = 'RW access to PROD_BRONZE_DB';
CREATE ROLE IF NOT EXISTS AR_PROD_SILVER_ALL_RO COMMENT = 'RO access to PROD_SILVER_DB';
CREATE ROLE IF NOT EXISTS AR_PROD_SILVER_ALL_RW COMMENT = 'RW access to PROD_SILVER_DB';
CREATE ROLE IF NOT EXISTS AR_PROD_GOLD_ALL_RO   COMMENT = 'RO access to PROD_GOLD_DB';
CREATE ROLE IF NOT EXISTS AR_PROD_GOLD_ALL_RW   COMMENT = 'RW access to PROD_GOLD_DB';

-- ---- Schema-Level Access Roles (for sensitive schemas) ----
CREATE ROLE IF NOT EXISTS AR_PROD_BRONZE_EPIC_RO COMMENT = 'RO access to EPIC schema in PROD_BRONZE_DB';
CREATE ROLE IF NOT EXISTS AR_PROD_BRONZE_EPIC_RW COMMENT = 'RW access to EPIC schema in PROD_BRONZE_DB';
CREATE ROLE IF NOT EXISTS AR_PROD_BRONZE_SAP_RO  COMMENT = 'RO access to SAP schema in PROD_BRONZE_DB';
CREATE ROLE IF NOT EXISTS AR_PROD_BRONZE_SAP_RW  COMMENT = 'RW access to SAP schema in PROD_BRONZE_DB';

-- ---- Unmask Role ----
CREATE ROLE IF NOT EXISTS AR_PROD_UNMASK COMMENT = 'Exemption role for data masking — see unmasked PII';

-- ---- Grants: PROD_BRONZE_DB ----
GRANT USAGE ON DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RO;
GRANT USAGE ON DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RW;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RW;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RO;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RW;

GRANT SELECT ON ALL TABLES IN DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RO;
GRANT SELECT ON FUTURE TABLES IN DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RO;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE PROD_BRONZE_DB TO ROLE AR_PROD_BRONZE_ALL_RW;

-- ---- Grants: PROD_SILVER_DB ----
GRANT USAGE ON DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RO;
GRANT USAGE ON DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RW;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RW;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RO;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RW;

GRANT SELECT ON ALL TABLES IN DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RO;
GRANT SELECT ON FUTURE TABLES IN DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RO;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE PROD_SILVER_DB TO ROLE AR_PROD_SILVER_ALL_RW;

-- ---- Grants: PROD_GOLD_DB ----
GRANT USAGE ON DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RO;
GRANT USAGE ON DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RW;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RW;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RO;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RW;

GRANT SELECT ON ALL TABLES IN DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RO;
GRANT SELECT ON FUTURE TABLES IN DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RO;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RW;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE PROD_GOLD_DB TO ROLE AR_PROD_GOLD_ALL_RW;

-- ---- Grant Access Roles to SYSADMIN ----
GRANT ROLE AR_PROD_BRONZE_ALL_RO TO ROLE SYSADMIN;
GRANT ROLE AR_PROD_BRONZE_ALL_RW TO ROLE SYSADMIN;
GRANT ROLE AR_PROD_SILVER_ALL_RO TO ROLE SYSADMIN;
GRANT ROLE AR_PROD_SILVER_ALL_RW TO ROLE SYSADMIN;
GRANT ROLE AR_PROD_GOLD_ALL_RO   TO ROLE SYSADMIN;
GRANT ROLE AR_PROD_GOLD_ALL_RW   TO ROLE SYSADMIN;
GRANT ROLE AR_PROD_UNMASK         TO ROLE SYSADMIN;


-- ============================================================================
-- SECTION 2: DYNAMIC DATA MASKING POLICIES
-- ============================================================================

USE ROLE SYSADMIN;

-- Full mask for SSN
CREATE OR REPLACE MASKING POLICY PROD_SILVER_DB.COMMON.SSN_MASK AS
    (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('AR_PROD_UNMASK') THEN val
        ELSE '***-**-' || RIGHT(val, 4)
    END
    COMMENT = 'Partial mask for SSN — shows last 4 digits only';

-- Full mask for Email
CREATE OR REPLACE MASKING POLICY PROD_SILVER_DB.COMMON.EMAIL_MASK AS
    (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('AR_PROD_UNMASK') THEN val
        ELSE '****@' || SPLIT_PART(val, '@', 2)
    END
    COMMENT = 'Masks email username, preserves domain';

-- Full mask for Phone
CREATE OR REPLACE MASKING POLICY PROD_SILVER_DB.COMMON.PHONE_MASK AS
    (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('AR_PROD_UNMASK') THEN val
        ELSE '***-***-' || RIGHT(val, 4)
    END
    COMMENT = 'Partial mask for phone — shows last 4 digits';

-- Full mask for Patient Name
CREATE OR REPLACE MASKING POLICY PROD_SILVER_DB.COMMON.NAME_MASK AS
    (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('AR_PROD_UNMASK') THEN val
        ELSE '** MASKED **'
    END
    COMMENT = 'Full mask for patient names';

-- Mask for DOB (date type)
CREATE OR REPLACE MASKING POLICY PROD_SILVER_DB.COMMON.DOB_MASK AS
    (val DATE) RETURNS DATE ->
    CASE
        WHEN CURRENT_ROLE() IN ('AR_PROD_UNMASK') THEN val
        ELSE DATE_FROM_PARTS(YEAR(val), 1, 1)  -- Returns Jan 1 of birth year only
    END
    COMMENT = 'Masks DOB to year only';

-- Apply masking policies to columns (example):
-- ALTER TABLE PROD_SILVER_DB.EPIC.PATIENTS
--     MODIFY COLUMN SSN SET MASKING POLICY PROD_SILVER_DB.COMMON.SSN_MASK;
-- ALTER TABLE PROD_SILVER_DB.EPIC.PATIENTS
--     MODIFY COLUMN EMAIL SET MASKING POLICY PROD_SILVER_DB.COMMON.EMAIL_MASK;


-- ============================================================================
-- SECTION 3: FUNCTIONAL ROLES
-- ============================================================================

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS FR_PROD_PLATFORM_ADMIN         COMMENT = 'PROD platform admin';
CREATE ROLE IF NOT EXISTS FR_PROD_DATA_ENGG_ADMIN        COMMENT = 'Data Engineering admin';
CREATE ROLE IF NOT EXISTS FR_PROD_DATA_ENGG_DEVELOPER    COMMENT = 'Data Engineering developer';
CREATE ROLE IF NOT EXISTS FR_PROD_ANALYTICS_ANALYST      COMMENT = 'Analytics analyst';
CREATE ROLE IF NOT EXISTS FR_PROD_ANALYTICS_VIEWER       COMMENT = 'Analytics viewer';
CREATE ROLE IF NOT EXISTS FR_PROD_MANAGERS_VIEWER        COMMENT = 'Manager viewer';
CREATE ROLE IF NOT EXISTS FR_PROD_DATA_SCIENCE_DEVELOPER COMMENT = 'Data Science developer';
CREATE ROLE IF NOT EXISTS FR_PROD_ETL_SERVICE            COMMENT = 'Fivetran ETL service';
CREATE ROLE IF NOT EXISTS FR_PROD_DBT_SERVICE            COMMENT = 'dbt service';

-- Access role grants
GRANT ROLE AR_PROD_BRONZE_ALL_RW TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT ROLE AR_PROD_SILVER_ALL_RW TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT ROLE AR_PROD_GOLD_ALL_RW   TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT ROLE AR_PROD_UNMASK         TO ROLE FR_PROD_PLATFORM_ADMIN;

GRANT ROLE AR_PROD_BRONZE_ALL_RW TO ROLE FR_PROD_DATA_ENGG_ADMIN;
GRANT ROLE AR_PROD_SILVER_ALL_RW TO ROLE FR_PROD_DATA_ENGG_ADMIN;
GRANT ROLE AR_PROD_GOLD_ALL_RO   TO ROLE FR_PROD_DATA_ENGG_ADMIN;

GRANT ROLE AR_PROD_BRONZE_ALL_RW TO ROLE FR_PROD_DATA_ENGG_DEVELOPER;
GRANT ROLE AR_PROD_SILVER_ALL_RW TO ROLE FR_PROD_DATA_ENGG_DEVELOPER;

GRANT ROLE AR_PROD_SILVER_ALL_RO TO ROLE FR_PROD_ANALYTICS_ANALYST;
GRANT ROLE AR_PROD_GOLD_ALL_RO   TO ROLE FR_PROD_ANALYTICS_ANALYST;

GRANT ROLE AR_PROD_GOLD_ALL_RO TO ROLE FR_PROD_ANALYTICS_VIEWER;
GRANT ROLE AR_PROD_GOLD_ALL_RO TO ROLE FR_PROD_MANAGERS_VIEWER;

GRANT ROLE AR_PROD_SILVER_ALL_RO TO ROLE FR_PROD_DATA_SCIENCE_DEVELOPER;
GRANT ROLE AR_PROD_GOLD_ALL_RW   TO ROLE FR_PROD_DATA_SCIENCE_DEVELOPER;

GRANT ROLE AR_PROD_BRONZE_ALL_RW TO ROLE FR_PROD_ETL_SERVICE;
GRANT ROLE AR_PROD_SILVER_ALL_RW TO ROLE FR_PROD_ETL_SERVICE;

GRANT ROLE AR_PROD_SILVER_ALL_RW TO ROLE FR_PROD_DBT_SERVICE;
GRANT ROLE AR_PROD_GOLD_ALL_RW   TO ROLE FR_PROD_DBT_SERVICE;

-- Hierarchy: all functional roles → SYSADMIN
GRANT ROLE FR_PROD_PLATFORM_ADMIN         TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_DATA_ENGG_ADMIN        TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_DATA_ENGG_DEVELOPER    TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_ANALYTICS_ANALYST      TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_ANALYTICS_VIEWER       TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_MANAGERS_VIEWER        TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_DATA_SCIENCE_DEVELOPER TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_ETL_SERVICE            TO ROLE SYSADMIN;
GRANT ROLE FR_PROD_DBT_SERVICE            TO ROLE SYSADMIN;


-- ============================================================================
-- SECTION 4: WAREHOUSE GRANTS
-- ============================================================================

GRANT USAGE ON WAREHOUSE PROD_ETL_WH       TO ROLE FR_PROD_DATA_ENGG_ADMIN;
GRANT USAGE ON WAREHOUSE PROD_ETL_WH       TO ROLE FR_PROD_DATA_ENGG_DEVELOPER;
GRANT USAGE ON WAREHOUSE PROD_ETL_WH       TO ROLE FR_PROD_ETL_SERVICE;
GRANT USAGE ON WAREHOUSE PROD_ETL_WH       TO ROLE FR_PROD_DBT_SERVICE;
GRANT USAGE ON WAREHOUSE PROD_ANALYTICS_WH TO ROLE FR_PROD_ANALYTICS_ANALYST;
GRANT USAGE ON WAREHOUSE PROD_ANALYTICS_WH TO ROLE FR_PROD_ANALYTICS_VIEWER;
GRANT USAGE ON WAREHOUSE PROD_ADHOC_WH     TO ROLE FR_PROD_MANAGERS_VIEWER;
GRANT USAGE ON WAREHOUSE PROD_DS_WH        TO ROLE FR_PROD_DATA_SCIENCE_DEVELOPER;

-- Platform admin: USAGE + OPERATE
GRANT USAGE, OPERATE ON WAREHOUSE PROD_ETL_WH       TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE PROD_ANALYTICS_WH TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE PROD_ADHOC_WH     TO ROLE FR_PROD_PLATFORM_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE PROD_DS_WH        TO ROLE FR_PROD_PLATFORM_ADMIN;
